package:
    name: pybot
    version: 0.2

source:
    git_url: https://github.com/spillai/pybot.git
    git_branch: py35

# source:
#     path: /Users/spillai/pybot

build:
    number: 0

requirements:
    build:
        - cmake
        - python
        - numpy
        - pip
        - wheel
        - opencv3 >=3.1.0 # [py35 and py36]
        - eigen
        - gflags
        - glog
        - boost ==1.59.0
    run:
        - python
        - numpy
        - scipy
        - protobuf ==3.4.1
        - pyzmq
        - opencv3 >=3.1.0 # [py35 and py36]
        - eigen
        - matplotlib
        - pytables
        - pandas

    test:
      imports:
        - pybot
        - pybot.vision
        - pybot.utils
        - pybot.geometry
        - pybot.externals

    commands:
        - python -c "import pybot.vision; import pybot.utils; import
          pybot.externals; import pybot.geometry;"

about:
    license: MIT
    summary: Research tools for autonomous systems using Python
