FROM spillai/pybot-docker-base

COPY . /source/pybot

WORKDIR /source/pybot

# CHANGE THIS TO CONDA BUILD/DEVEL
# conda env create -f environment.yml --name pybot
# conda install -c s_pillai pybot -n pybot


# RUN pip install -r requirements.txt && \
#     python setup.py build
